# Generated by Django 4.2.20 on 2025-04-02 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
