# Generated by Django 4.2.20 on 2025-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'Активное'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
