# Generated by Django 4.2.20 on 2025-03-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_bio_alter_userprofile_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
