# Generated by Django 4.2.20 on 2025-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_pdfs/'),
        ),
    ]
